apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: analyzer-templates
  namespace: argo-analyzer
spec:
  volumes:
    - name: argo-analyzer-training-volume
      persistentVolumeClaim:
        claimName: argo-analyzer-training-data
    - name: argo-analyzer-validation-volume
      persistentVolumeClaim:
        claimName: argo-analyzer-validation-data
    - name: argo-analyzer-testing-volume
      persistentVolumeClaim:
        claimName: argo-analyzer-testing-data
    - name: shm-volume
      emptyDir:
        medium: Memory

  templates:

    - name: train-model
      inputs:
        parameters:
          - name: model_path
          - name: batch_size
          - name: shuffle
          - name: num_workers
          - name: model_dropout
          - name: training_weight_decay
          - name: training_learning_rate
          - name: training_epochs
      container:
        image: eliteabhi/analyzer:argo
        imagePullPolicy: Always
        workingDir: /app
        command: [ "python" ]
        args: [ "src/main.py" ]
        env:
          - name: DATASETS_PATH
            value: "/mnt/data/"
          - name: SAVED_MODEL_PATH
            value: "{{inputs.parameters.model_path}}"
          - name: TRAIN
            value: "1"
          - name: DATASET_BATCH_SIZE
            value: "{{inputs.parameters.batch_size}}"
          - name: DATASET_SHUFFLE
            value: "{{inputs.parameters.shuffle}}"
          - name: DATASET_NUM_WORKERS
            value: "{{inputs.parameters.num_workers}}"
          - name: TRAINING_EPOCHS
            value: "{{inputs.parameters.training_epochs}}"
          - name: TRAINING_LEARNING_RATE
            value: "{{inputs.parameters.training_learning_rate}}"
          - name: MODEL_DROPOUT
            value: "{{inputs.parameters.model_dropout}}"
          - name: TRAINING_WEIGHT_DECAY
            value: "{{inputs.parameters.training_weight_decay}}"
        volumeMounts:
          - name: argo-analyzer-training-volume
            mountPath: /mnt/data/
          - name: shm-volume
            mountPath: /dev/shm
        securityContext:
          privileged: true
        nodeSelector:
          kubernetes.io/hostname: main-server
        resources:
          requests:
            cpu: "2"
          limits:
            cpu: "4"
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"

    - name: validate-model
      inputs:
        parameters:
          - name: model_path
          - name: evaluation_threshold
      container:
        image: eliteabhi/analyzer:argo
        imagePullPolicy: Always
        workingDir: /app
        command: [ "python" ]
        args: [ "src/main.py" ]
        env:
          - name: DATASETS_PATH
            value: "/mnt/data/"
          - name: SAVED_MODEL_PATH
            value: "{{inputs.parameters.model_path}}"
          - name: TRAIN
            value: "0"
          - name: EVALUATE
            value: "1"
          - name: EVALUATION_THRESHOLD
            value: "{{inputs.parameters.evaluation_threshold}}"
        volumeMounts:
          - name: argo-analyzer-validation-volume
            mountPath: /mnt/data/
          - name: shm-volume
            mountPath: /dev/shm
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: "500m"
          limits:
            cpu: "2"
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"

    - name: test-model
      inputs:
        parameters:
          - name: model_path
          - name: evaluation_threshold
      container:
        image: eliteabhi/analyzer:argo
        imagePullPolicy: Always
        workingDir: /app
        command: [ "python" ]
        args: [ "src/main.py" ]
        env:
          - name: DATASETS_PATH
            value: "/mnt/data/"
          - name: SAVED_MODEL_PATH
            value: "{{inputs.parameters.model_path}}"
          - name: TRAIN
            value: "0"
          - name: TEST
            value: "1"
          - name: EVALUATION_THRESHOLD
            value: "{{inputs.parameters.evaluation_threshold}}"
        volumeMounts:
          - name: argo-analyzer-testing-volume
            mountPath: /mnt/data/
          - name: shm-volume
            mountPath: /dev/shm
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: "500m"
          limits:
            cpu: "2"
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
