apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: analyzer-templates
  namespace: argo-analyzer
spec:
  volumes:
    - name: argo-analyzer-training-volume
      persistentVolumeClaim:
        claimName: argo-analyzer-training-data
    - name: argo-analyzer-validation-volume
      persistentVolumeClaim:
        claimName: argo-analyzer-validation-data
    - name: argo-analyzer-testing-volume
      persistentVolumeClaim:
        claimName: argo-analyzer-testing-data
    - name: shm-volume
      emptyDir:
        medium: Memory

  templates:

    - name: train-model
      container:
        image: eliteabhi/analyzer:argo
        imagePullPolicy: Always
        workingDir: /app
        command: [ "python" ]
        args: [ "src/main.py" ]
        env:
          - name: DATASETS_PATH
            value: "/mnt/data/"
          - name: SAVED_MODEL_PATH
            value: "/mnt/data/saved_models/BinaryAlexNet/model.pt"
          - name: TRAIN
            value: "1"
          - name: DATASET_BATCH_SIZE
            value: "32"
          - name: DATASET_SHUFFLE
            value: "1"
          - name: DATASET_NUM_WORKERS
            value: "4"
          - name: DATASET_PIN_MEMORY
            value: "1"
          - name: NUM_EPOCHS
            value: "10"
          - name: LEARNING_RATE
            value: "0.001"
        volumeMounts:
          - name: argo-analyzer-training-volume
            mountPath: /mnt/data/
          - name: shm-volume
            mountPath: /dev/shm
        securityContext:
          privileged: true
        nodeSelector:
          kubernetes.io/hostname: main-server
        resources:
          requests:
            cpu: "2"
          limits:
            cpu: "4"
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"

    - name: validate-model
      container:
        image: eliteabhi/analyzer:argo
        imagePullPolicy: Always
        workingDir: /app
        command: [ "python" ]
        args: [ "src/main.py" ]
        env:
          - name: DATASETS_PATH
            value: "/mnt/data/"
          - name: SAVED_MODEL_PATH
            value: "/mnt/data/saved_models/BinaryAlexNet/model.pt"
          - name: EVALUATE
            value: "1"
          - name: DATASET_BATCH_SIZE
            value: "32"
          - name: DATASET_SHUFFLE
            value: "0"
          - name: DATASET_NUM_WORKERS
            value: "4"
          - name: DATASET_PIN_MEMORY
            value: "1"
        volumeMounts:
          - name: argo-analyzer-validation-volume
            mountPath: /mnt/data/
          - name: shm-volume
            mountPath: /dev/shm
        securityContext:
          privileged: true
        nodeSelector:
          kubernetes.io/hostname: main-server
        resources:
          requests:
            cpu: "2"
          limits:
            cpu: "4"
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"

    - name: test-model
      container:
        image: eliteabhi/analyzer:argo
        imagePullPolicy: Always
        workingDir: /app
        command: [ "python" ]
        args: [ "src/main.py" ]
        env:
          - name: DATASETS_PATH
            value: "/mnt/data/"
          - name: SAVED_MODEL_PATH
            value: "/mnt/data/saved_models/BinaryAlexNet/model.pt"
          - name: TEST
            value: "1"
          - name: DATASET_BATCH_SIZE
            value: "32"
          - name: DATASET_SHUFFLE
            value: "0"
          - name: DATASET_NUM_WORKERS
            value: "4"
          - name: DATASET_PIN_MEMORY
            value: "1"
        volumeMounts:
          - name: argo-analyzer-testing-volume
            mountPath: /mnt/data/
          - name: shm-volume
            mountPath: /dev/shm
        securityContext:
          privileged: true
        nodeSelector:
          kubernetes.io/hostname: main-server
        resources:
          requests:
            cpu: "2"
          limits:
            cpu: "4"
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"