apiVersion: v1
kind: Namespace
metadata:
  name: argo-analyzer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: argo-analyzer-pv
  namespace: argo-analyzer
spec:
  storageClassName: nfs
  volumeMode: Filesystem
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
  nfs:
    path: /media/k8-data/argo/analyzer
    server: 192.168.1.25
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argo-analyzer-training-data
  namespace: argo-analyzer
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argo-analyzer-validation-data
  namespace: argo-analyzer
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argo-analyzer-testing-data
  namespace: argo-analyzer
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
